name: dreye
channels:
  - conda-forge
dependencies:
  - seaborn>=0.10
  - pint>=0.16.1
  - scikit-learn>=1.0
  - pandas>=1.0
  - cvxpy>=1.1.10
  - pyarrow>=3.0.0
  - quadprog
  - scipy>=1.9.0
  - matplotlib
  - numpy
  - tqdm